controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    game.setDialogTextColor(7)
    game.setDialogFrame(img`
        a a a a a a a a a a a a a a a 
        a c c c c c c c c c c c c c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c f f f f f f f f f f f c a 
        a c c c c c c c c c c c c c a 
        a a a a a a a a a a a a c a a 
        . . . . . . . . . . . a . . . 
        `)
    game.showLongText("Destroy or dodge the asteroids!\\nSurvive for 1 second = 10pts\\ndestroy an asteroid = 100pts", DialogLayout.Bottom)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . 5 5 . . . . . . . 
        . . . . . . 5 4 4 5 . . . . . . 
        . . . . . 5 4 2 2 4 5 . . . . . 
        . . . . 5 4 2 1 1 2 4 5 . . . . 
        . . . . 5 4 2 1 1 2 4 5 . . . . 
        . . . . 5 4 2 1 1 2 4 5 . . . . 
        . . . . 5 4 2 1 1 2 4 5 . . . . 
        . . . . 5 4 2 1 1 2 4 5 . . . . 
        . . 5 . . 5 4 2 2 4 5 . . . . . 
        . . . . . . 5 2 2 5 . . . . . . 
        . . . . . . 5 4 4 5 . . . 5 . . 
        . . . . . . 5 5 5 5 . . . . . . 
        . . . . . . 5 5 5 5 . . . . . . 
        . . . . . . . 5 5 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 0, -50)
    projectile.lifespan = 4000
    music.pewPew.play()
    pause(1000)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    info.changeScoreBy(100)
    music.jumpDown.play()
    rock.destroy(effects.fire, 100)
    projectile.destroy()
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    rock.destroy(effects.warmRadial, 200)
    music.powerDown.play()
    pause(500)
    info.changeLifeBy(-1)
})
info.onLifeZero(function () {
    game.over(true, effects.smiles)
})
let rock: Sprite = null
let projectile: Sprite = null
let mySprite: Sprite = null
effects.confetti.startScreenEffect(1000)
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffff5fffffffff4ffffffffff5ffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fff5fffffffffffffffffffffff7fffffffffffffffffffff77ffffffffff7777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffff7fffffffffffffffffffff77ffffffff77ffff7fffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffff77fffffffffffffffff77fffffffff77ffffffff7777ffffff77ffffffffffffffffffffffff3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffff77fffffffffffffffff77fffffffff77ffffffff7fff7fffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffff77fffffffff7ffffff7f7ffffffff777ffffff77fff77ffff777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffff77ffffffff77fffff7f77fffffff7f7ffffff7fffff77fffff777ffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffff77fffffff77ffffff7ff7fffffff7f7fffff77ffffff7ffffffff7777777fffffffffffffff4ffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffff4ffffff77fffff77fffffff7fff7ffffff7ff7ffff7fffffff7ffffffffffffff7fffffffffffffffffffffffffff3ffffffff5ffffff4fffffffffffffffffffffffff3ffffffffffffffffffff
    ffffffffffff77fff77ffffffff7fff7ffffff7ff77fff7ffffffff7fffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4ffffffffffffffffffffffffffff
    ffffffffffff77f777fffffffff7fff77ffff77fff7fff7ffffff7777ffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffff777fffffffffff7ffff7ffff7ffff7fff7ff7777ff7ffffffffffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffff
    fffffffffffff77ffffffffffff7fffff7fff7ffff7fff7ffffffff7fffffffffff77ffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffff
    ffffffffffff7777fffffffffff7fffff7ff7fffff77ff7fffffffff7fffff77777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffff7ff77ffffffffff7ffffff7f7ffffff7ff7fffffffff7ffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffff777777fffffffffffffffffff
    ffffffffff77ffff77fffffffff7ffffff777ffffff7ff7ffffffff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffff7fffffffffffffffffff
    fff5fffff77ffffff77ffffffff7fffffff7fffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77fffff7ffffffffffffffffff
    fffffffff77fffffff777ffffffffffffff7fffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffff4fffffff
    ffffffff77ffffffffff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffff
    ffffffff7ffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77fffffffffff77777ffffff77ffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777777ffffffff7ffffffff777ffffffffffff7fff77fffffff7777ffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffff7fffff7777777777777fff77777ffff777ffff7ffffffffff77777ffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77ffffffffffffff7ffffffffff77fffffffff77ffff7ffffffffffffff77fffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffff7fffffffffffffff77fffffffff7ffffffffff7777777fffffffffffffff7ffffffff5ffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777ffffffffff777ffffffffffffff7ffffffff7fffffffffff777fffffffffffffffffff77ffffffffffffff
    fffff3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ff7ffffffffffff77ffffffffffff77fffffff7ffffffffffff7f7777fffffffffffffff7fffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff7777777fffffffffffffffffff7ff77fffffffffffff7777fffffffff7ffffff77ffff777fffff77ffff777fffff77777777fffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffff7ffffff77ffffffffffffffffff7ffff7fffffffffffffff777fffffff77fffff77ff77fffffffff7ffffff777ffffffffffffffffffffffffff
    ffffffffffffffffffff5fffffffffffffffffffffffffffffff7ffff7fffffffffffff7fffff77fffffffffffffff7ffffffff7ffffff7fffffffffffff7fffffffff77ffffffffffffffffffffffff
    ffffffffffffffffffffffffffffff3fffffffffff7ffffffff77fffff7ffffffffffff7ffffff7fffffffffffffff7ffffffff77fffff77fffff77fffff7fffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff7fffffff77ffffff7ffffffffffff7ffffff77f7fffffffffff77fffffffff7ffffff7777777fffffffffffffffffffffffffffffff5ffffffffff
    ffffffffff5ffff4ffffffffffffffffffffffffff7ffff7777777ffff7ffffffffffff7fff7777777fffffff77777ffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffff5fffff7ffff7fffff77fff7fffffffffffff7f77fffff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffff3ffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff7fffffffffff7fff7fffffffffffff7fffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff7fffffffffff7fff7fffffffffffff7fffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffff7ffffffffff77fff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffff4fffff7ffffffffff7ffff7777777777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4ff5ffffffffffffffffffffffffffffff
    fffffffffffffffffffffff555ffffffffffffffff7ff77777777fffff77fffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffff5fffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffff5555fffffffffffffff7ff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9999ffffffffffffffffffff
    ffffffffffffffffffffff55555fffffffffffffff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9ff9ffffffffffffffffffff
    ffffffffffffffffffff5555555555ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3fffffffffffffffffffffffffffffff9fffffffffffff9f99ffffffffffffffffffff
    ffffffffffffffffffff555555555ffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffff5fffffff4fffffffffffffff999fffffffffffff999fffffffffffffffffffff
    ffffffffffffffffffffff555555ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff99fffffff99999ffff99999999ffffffffffffffff
    fffffffffffffffffffffff5555ffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffff99ffffffff99fff999ff99ffff9999ffffffffffffff
    ffffffffffffffffffffff55555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9fffffffff9ffffff9fff9ffffffffffffffffffffff
    fffffffffffffffffffff5555555ffffffffffff5fffffffffffffffffffffffffffffffffffff4ffffffffffffffffffffffffffffffffffff99fffffffff9ffffff9ffffffffffffffffffffffffff
    ffffffffffffffffffff555577555fffffffffffffffffffffffffff3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff9fffffffff99ffff99ffffffffffffffffffffffffff
    ffffffffffffffffffff555777555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff999999ffffff99999fffffffffffffffffffffffffff
    fffffffffffffffffff777777777ffffffffffffffffffffffffffffffffffffff2222bbfffffffffffff331133fffffffffffffffffffffffff999fffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff77777777777ffffffffffffffffffffff5ffffffffffffff222dbbffffaaaaaafff31b1b3ff559599ffabcbabfffffffff99ffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff7777777777777ffffffffffffffffffffffffffffffffffffdfdfdbffffaaaaaafff311113ff559999ffbcbabafffffffff99ffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff733377777777777ffffffffffffffff4ffffffffffffffffffb1d11bffff79aaaafff339933ff995999ffabbcabfffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffff7777333777777777777ffffffffffffffffffffffffffffffffffb1111bffff79aaaafff319113ff599991ffacabaafffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffff77777333777777777777ffffffffffffffffffffffffffffffffff222111ffff7777aafff119111ff991117ffcababcfffffffffffffffffffffffffffffffffffffffffffffff9fffff
    fffffffffff7775557777999777555777fffffffffffffffffffffffffffffffff222222ffff77ff7afff111111ff117777ffabacaafffffffffffffffffffffffffffffffffffffffffff9fff9fffff
    fffffffffff77755577779997775557777ffffffffffffffffffffffffffffffff222222ffffccffccfff311113ff77c777ffcaacabfffffffffffffffffffffffffffffffffffffffffff99ff9fffff
    ffffffffff7777555777799977755577777fffffffffffffffffffffffffffffffdff5f2ffffccccccfff331133ff777777ffbcbacafffffffffffffffffffffffffffffffffffffffffff99999fffff
    fffffffff777777777777777777777777777ffffffffffffffffffffffffffffffdd2222ffffccccccfff111111ff777777ffaacabcfffffffffffffffffffffffffffffffffffffffffff9ff99fffff
    fffffffff7777777777777777777777777777ffffffffffffffffffffffff11111111111111111111111111111111111111111111111111fffffffffffffffffffffffffffffffffff9fff9fff9fffff
    fffffff777777777777777777777777333777ffffffffffffffffffffffff111111111111111111111111111111111111111111111111d1fffffffffffffffffffffffffffffffffff99ff9fff9fffff
    fffffff7777444777777777777777773337777fffffffffffffffffffffff111111111111111111111111111111111111111111111111d1ffffffffffffffffffffffffffffffff9fff9ff9fffffffff
    ffffff777774447777775557777777733377777ffffffffffffffffffffff1dddddddddddddddddddddddddddddddddddddddddddddddd1fffffffffff99fffffffffffffffffff99ff9ffffffffffff
    ffffff777774447777775557777777777777777ffffffffffffffffffffff11111111111111111111111111111111111111111111111111ffffffffff99ffffffffffffffffffff9f9f9ffffffffffff
    fffff77777777777777755577777777777777777ffffffffffffffffffffff11111dddddddddddddddddddddddddddddddddddddd11111ffffffffff99fffffffffffffffff9fff9ff99ffffffffffff
    ffff777777777777777777777777777777777777ffffffffffffffffffffff1d111dddddddddddddddddddddddddddddddddddddd1d111fffffff9999fffffffffffff9ffff9fff9fff9ffffffffffff
    ffff7777777777777777777777777777ffffffffffffffffffffffffffffff1d111ddbddddddbdddddbdddddbdddddbddddddbddd1d111fffffff9fffffffffffffffff99ff9fff9ffffffffffffffff
    fffffffffffffff77777777774447777ffffffffffffffffffffffffffffff1d111dddddddddddddddddddddddddddddddddddddd1d111ffffff99ffffffff9fffffffff99f9fff9ffffffffffffffff
    fffffffffffffff777777777744477777fffffffffffffffffffffffffffff1d111dddddddddddddddddddddddddddddddddddddd1d111ffffff99ffffffff9ffffffffff999ffffffffffffffffffff
    ffffffffffffff77777777777444777777ffffffffffffffffffffffffffff1d111dddddddddddddddddddddddddddddddddddddd1d111ffffff999fffffff9ffffffffffff9ffffffffffffffffffff
    fffffffffffff777779997777777777777ffffffffffffffffffffffffffff1d111dddddbdddddbddddddbdddddbdddddbddddddd1d111fffffff99fffffff9ffffffffffff9ffffffffffffffffffff
    ffffffffffff77777799977777777777777fffffffffffffffffffffffffff1d111dddddddddddddddddddddddddddddddddddddd1d111fffffff99ff99fff99ffff999fff99ffffffffffffffffffff
    ffffffffff7777777799977777777777777fffffffffffffffffffffffffff1d111dddddddddddddddddddddddddddddddddddddd1d111fffffff99999fffff99999ffffff9fffffffffffffffffffff
    fffffffff777777777777777777777777777ffffffffffffffffffffffffff1d111ddbdddddddddddddddddddddddddddddddddbd1d111fffffff999fffffff9ffffffffffffffffffffffffffffffff
    ffffffff77777777777777777777777777777fffffffffffffffffffffffff1d111ddddddddffffffffffffffffffffffdddddddd1d111fffffff999ffffffffffffffffffffffffffffffffffffffff
    fffffff777777777777777777777777777777fffffffffffffffffffffffff1d111ddddddddffffff5fffffffffffffffdddddddd1d111ffffffff99ffffffffffffffffffffffffffffffffffffffff
    fffffff7777777444777777777777777777777ffffffffffffffffffffffff1d111ddddddddfff4ffffffffff5fffffffdddbdddd1d111ffffffff99ffffffffffffffffffffffffffffffffffffffff
    ffffff777777774447777773337777777777777fffffffffffffffffffffff1d111ddddddddfffffff4f555ffffffffffdddddddd1d111ffffffff99ffffffffffffffffffffffffffffffffffffffff
    fffff77777777744477777733377777777555777ffffffffffffffffffffff1d111dddddbddff5555fff544f4ff555fffdddddddd1d111ffffffff99ffffffffffffffffffffffffffffffffffffffff
    ffff7777777777777777777333777777775557777fffffffffffffffffffff1d111ddddddddff5255ff5545ffff544fffdddddddd1d111fffffffff9ffffffffffffffffffffffffffffffffffffffff
    ffff7333777777777777777777777777775557777fffffffffffffffffffff1d111ddddddddff5445555445fff5445f5fdddddbdd1d111ffffffffffffffffffffffffffffffffffffffffffffffffff
    fff773337777777777777777777777777777777777ffffffffffffffffffff1d111ddddddddff5245554455f555445fffdddddddd1d111ffffffffffffffffffffffffffffff44444fffffffffffffff
    ff77733377777777777777777777777777777777777fffffffffffffffffff1d111ddddddddff542454455ff544445fffdddddddd1d111fffffffffffffffffffffff44444f44fff4fffffffffffffff
    f777777777777777799977777777777777777777777fffffffffffffffffff1d111ddbdddddfff54445445ff52255ffffddbddddd1d111ffffffffffffffffffffff44fff4f4ffff4fffffffffffffff
    f77777777777777779997777777777777fffffffffffffffffffffffffffff1d111ddddddddfff5424424555424ffffffdddddddd1d111ffffffffffffffffffffff44fff4449944449999999996ffff
    ffffffffffff7777799977777777777777ffffffffffffffffffffffffffff1d111ddddddddfff54222224224245fffffdddddddd1d111ffffffffffffffffffffff44ff44444444499999999969ffff
    ffffffffff7777777777777777777777777fffffffffffffffffffffffffff1d111dddddbddfff55421222221245fffffdddddbdd1d111ffffffffffffffffffffff44ff44444444444444444699ffff
    ffffffffff77777777777777777777777777ffffffffffffffffffffffffff1d111ddddddddfffff522122212245fffffdddddddd1d111fffffffffffffffffffffff44449444444444444466999ffff
    fffffffff7777777777777777774447777777fffffffffffffffffffffffff1d111ddddddddfffff54222122245ffffffdddddddd1d111ffffffffffffffffffffff999999944449999999664999ffff
    fffffff777777777777777777774447777777fffffffffffffffffffffffff1d111ddbdddddffffff22fffff2ffffffffdddddddd1d111ffffffffffffffffffff99999994444499999966644999ffff
    fffff777777777777777777777744477777777ffffffffffffffffffffffff1d111ddddddddfffffff2fceefffeecffffddbddddd1d111fffffffffffffffffff666666666666666666669944999ffff
    fff777777777777777777777777777777777777fffffffffffffffffffffff1d111ddddddddffffeecffceeeefeecffffdddddddd1d111fffffffffffffffffff999999994499999996999944999ffff
    fff7777777444777777777777777777777777777ffffffffffffffffffffff1d111dddddbddffffeecffceeeeeceeefffdddddddd1d111fffffffffffffffffff999999994499999996999944999ffff
    ff777777774447777555777777777777777799977fffffffffffffffffffff1d111ddddddddfffeceeeeeeeeeeeceeeffdddddbdd1d111fffffffffffffffffff999999994499999996999944999ffff
    f73337777744477775557777777777333777999777ffffffffffffffffffff1d111ddddddddfffeeceeeeccceeeecceffdddddddd1d111fffffffffffffffffff999999994499999996999944999ffff
    7733377777777777755577777777773337779997777fffffffffffffffffff1d111ddddddddfffeeeeeeefffcceeeeeffdddddddd1d111fffffffffffffffffff999999994499999996999944999ffff
    77333777777777777777777777777733377777777777ffffffffffffffffff11111ddddddddffffffffffffffffffffffdddddddd11111fffffffffffffffffff999999994499999996999944999ffff
    77777777777777777777777777777777777777777777bbbbbbbbbbbbbeeeee11111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee11111eeeeebbbbbbbbbbbbbb999999994499999996999944999bbbb
    bbbbbbbbbbbbbbbbbbeceeeee7777bbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeececebbbbbbbbbbbbbb999999994499999996999944999bbbb
    bbbbbbbbbbbbbbbbbbeceeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeecccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeccccccecebbbbbbbbbbbbbb999999994499999996999944999bbbb
    bbbbbbbbbbbbbbbbbbeceeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccebbbbbbbbbbbbbb99999999449999999699994499bbbbb
    bbbbbbbbbbbbbbbbbbeceeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeceeebbbbbbbbbbbbbb9999999944999999969999449bbbbbb
    bbbbbbbbbbbbbbbbbbeceeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecebbbbbbbbbbbbbbbb99999999449999999699994bbbbbbbb
    bbbbbbbbbbbbbbbbbbeceeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccebbbbbbbbbbbbbbbb9999999944999999969999bbbbbbbbb
    bbbbbbbbbbbbbb222222222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeceeebbbbbbbbbbbbbbbb999999994499999996999bbbbbbbbbb
    bbbbbbbbbbbbbbb2a22222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccebbbbbbbbbbbbbbbbbb99999999449999999699bbbbbbbbbbb
    bbbbbbbbbbbbbbb2a22222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeecccccceeebbbbbbbbbbbbbbbbbbb99999994499999996bbbbbbbbbbbbb
    bbbbbbbbbbbbbbb2a22222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbb2a22222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbb22a2222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbb2aaaa222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbb22222222222bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    `)
music.playMelody("E G C5 B E C F E ", 150)
pause(3000)
scene.setBackgroundColor(0)
scene.setBackgroundImage(img`
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    ................................................................................................................................................................
    `)
effects.starField.startScreenEffect()
effects.confetti.endScreenEffect()
info.setScore(0)
info.setLife(3)
mySprite = sprites.create(sprites.space.spaceGreenShip, SpriteKind.Player)
mySprite.setPosition(80, 112)
mySprite.setFlag(SpriteFlag.StayInScreen, true)
tiles.setWallAt(tiles.getTileLocation(0, 0), true)
tiles.setWallAt(tiles.getTileLocation(160, 0), true)
game.onUpdateInterval(2000, function () {
    if (randint(1, 10) <= 2) {
        rock = sprites.create(sprites.space.spaceAsteroid2, SpriteKind.Enemy)
    } else {
        rock = sprites.create(sprites.space.spaceSmallAsteroid0, SpriteKind.Enemy)
    }
    rock.setPosition(randint(0, 160), 0)
    rock.lifespan = 4000
    if (info.score() > 2000) {
        rock.setVelocity(0, randint(50, 100))
    } else {
        rock.setVelocity(0, 50)
    }
})
game.onUpdateInterval(1000, function () {
    info.changeScoreBy(10)
    if (info.score() > 3000) {
        rock = sprites.create(sprites.space.spaceSmallAsteroid0, SpriteKind.Enemy)
        rock.lifespan = 4000
        rock.setPosition(randint(0, 160), 0)
        rock.setVelocity(0, randint(50, 150))
    }
})
forever(function () {
    controller.moveSprite(mySprite, 100, 0)
})
